sudo: required

language: go

services:
  - mysql
  - docker

before_install:
  - docker build -t smoketest . > /dev/null 2>&1

script:
  - docker run smoketest /bin/sh -c "make unittest"
  - test $TRAVIS_BRANCH = "master" &&
    docker run -v /var/run/docker.sock:/var/run/docker.sock smoketest /bin/sh -c "make full-smoketest; make destroy-smoketest"
