sudo: required

language: go
go:
- 1.12

services:
- docker

before_install:
- sudo apt-get install jq

  #script:
  #- make unittest

# Build binaries to upload
before_deploy:
 - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
 - go get github.com/blang/expenv
 - go install github.com/blang/expenv
 - pip3 install mkdocs
 - pip3 install -Iv mkdocs-material==3.0.6
 - make release

# Deploy to Github
deploy:
- provider: releases
  api_key: $DEPLOY_KEY
  file: 
   - build/macOS.zip
   - build/Linux.zip
   - build/Windows.zip
  skip_cleanup: true
  on:
    tags: true

